import Navigate from "@/components/Navigate"
import './globals.css'
export const metadata = {
  title: 'Prueba técnica auco',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body class='bg-gray-300'>
        <Navigate/>
        {children}
      </body>
    </html>
  )
}
